- name: install docker
  yum: name=docker state=present

- name: create docker.service directory
  file: path=/etc/systemd/system/docker.service.d state=directory

# for environment behind proxy
#- name: set http proxy for docker.service.d
#  blockinfile:
#    dest: '/etc/systemd/system/docker.service.d/http-proxy.conf'
#    create: yes
#    block: |
#      [Service]
#      Environment="HTTP_PROXY={{ http_proxy }}" "HTTPS_PROXY={{ https_proxy }}"
#  register: set_docker_proxy
  
- name: start docker.
  systemd: name=docker.service enabled=yes daemon_reload=yes state=restarted
  when: set_docker_proxy | changed

- name: install docker-py
  pip: name=docker-py

- name: build hadoop-docker images.
  docker_image:
    path: "{{ hadoop_dockerfile_dir }}"
    name: hadoop-docker
    state: present
#    buildargs:
#      http_proxy: "{{ http_proxy }}"
#      https_proxy: "{{ https_proxy }}"


